### ISSUE TITLE
Pretrained-model yet?

### ISSUE THREAD

**Issue by sbkim052** [mindslab-ai/cotatron#3]
Thank you for sharing this git.
I'm just wondering if the pre-trained model has yet to be uploaded. 
Will it be uploaded soon?

**Comment by seungwonpark** [comment]
Hi, thank you for your interest in our model.
Sorry for replying late, I was recently gone for mandatory military service from Jul. 16 to Aug. 13...

Due to other priorities, we cannot say for sure about the date of release. However, we promise to release it before the opening of INTERSPEECH 2020 (around late October). Even before that, please feel free to contact us or open an issue to ask a question about our model.

**Comment by seungwonpark** [comment]
We have just released the pre-trained model! Please refer to the updated README. @sbkim052
